### PR TITLE
Add all DLC items to automatic checklist

### PR DESCRIPTION
**Pull request by Clodolt**
- adds all weapons, armors, altered armor, magic, ash of war, summons and talismans to the checklist
- pulled item ids from various cheat engine tables
- added the new categories to item_dict and item_counter
- manually tested links to wiki

Notes:
- Images have not been added yet (I might look into pulling images from the wiki automatically instead of adding them manually)
- The items have been appended to the end of the jsons instead of sorted into them, to make editing dlc items and implementing a "show DLC items" filter easier

### CODE REVIEW

**Comment by CyberGiant7** [comment]
Thank you for your work. I tested it and everything seems to work, even the links to the wiki.

Unfortunately the problem with the images remains, I tried to search online if there was a source for the images but I didn't find anything so these days I try to make sure to get the images from the wiki and push your commit

**Comment by kingcreek** [comment]
@Clodolt you win this time, I'm working on it right now but you're fast, I'm making a separate .json file to add the option to load or not DLC items. Seeing as you're working on it I'll leave it to you, if you want you can take a look in my fork at how I was implementing it, feel free to use in ur code.

**Comment by Clodolt** [comment]
@CyberGiant7 I added all DLC images that were available on the wiki. For reference and future use, I wrote a python script to fetch them all for me:

`import json
import os
import requests
from lxml import html
from urllib.parse import quote

with open('data.json') as f:
    data = json.load(f)

base_url = 'https://eldenring.wiki.fextralife.com'

def fetch_and_save_image(name, item_type):
    try:
        encoded_name = quote(name.replace(" ", "+"))
        url = f'{base_url}/{encoded_name}'
        
        response = requests.get(url)
        response.raise_for_status()
        
        tree = html.fromstring(response.content)
        image_paths = tree.xpath('//*[@id="infobox"]/div/table/tbody/tr[2]/td/img/@src')
        
        if not image_paths:
            print(f'No image found for {name}')
            return
        
        image_path = image_paths[0]
        image_url = base_url + image_path
        
        image_response = requests.get(image_url)
        image_response.raise_for_status()
        
        directory = item_type
        os.makedirs(directory, exist_ok=True)
        
        sanitized_name = name.replace(":", "").replace("/", "_").replace("\\", "_")
        
        image_file_path = os.path.join(directory, f'{sanitized_name}.webp')
        
        with open(image_file_path, 'wb') as img_file:
            img_file.write(image_response.content)
        print(f'Successfully saved {name} image at {image_file_path}')
    except requests.exceptions.RequestException as e:
        print(f'Failed to fetch page or image for {name}: {e}')
    except IndexError:
        print(f'Image URL not found for {name}')
    except Exception as e:
        print(f'An error occurred while processing {name}: {e}')

for item_type, items in data.items():
    for item_id, item_info in items.items():
        name = item_info.get('name')
        fetch_and_save_image(name, item_type)
`

For some talismans (the upgraded versions of talismans) do not have a image on the wiki and I was not able to find a suitable one, but i guess thats fine for now until we get an icon pack.

**Comment by Clodolt** [comment]
thanks @kingcreek for your changes, I added them to the fork :)

**Comment by CyberGiant7** [comment]
Hi, I fixed some missing ids and restored the photos of the items that are not from the DLC as they were before, since the ones in the wiki have watermarks.

Thank you very much, you have been really helpful in this period when I don't have much time to devote to the website

**Pull request closed without merging**
